name: Node.js Build

on:
  push:
    branches:
      - '**'

    # release-it specs fail when running on tags.
    tags-ignore:
    - '**'

jobs:
  build:
    uses: dimensionalpocket/development-js/.github/workflows/default-node-build.yml@0.5.2
